### ISSUE TITLE
the catalog (Run... button) should support ConfigMap as well as Template for working on vanilla Kubernetes environments

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio-kubernetes#100]
for an example see this issue:
https://github.com/fabric8io/fabric8-maven-plugin/issues/20

basically gofabric8 and apps should allow apps to be packaged as ConfigMap 'catalog' entries so that we can work on vanilla k8s platforms and still have a 'catalog of apps to run' that folks can do the draggy/drop thing or edit etc.

All we'd need to do really is on vanilla kubernetes is not try to load templates at all - and then we also load ConfigMaps with some label selector (e.g. kind=catalog) and treat them kinda like Templates. 

The only difference is to run them, we'd iterate through the ConfigMap.data key/value pairs and treat each one as a resource (or Template). So shouldn't be too hard to add

**Comment by gashcrumb** [comment]
Think this is done...
