### ISSUE TITLE
lets combine ReplicaSet and ReplicationControllers in the model into a model.replicas and then view those in the Replicas UI?

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio-kubernetes#106]

**Comment by gashcrumb** [comment]
@jstrachan think this is all set now?

**Comment by jstrachan** [comment]
yes thanks!

**Comment by jimmidyson** [comment]
I haven't looked at what it looks like (sure it's awesome though!) but just wanted to check you've handled the new label selector format (in, not in, etc) in the UI somehow?

**Comment by jstrachan** [comment]
@jimmidyson we don't have any nice UI stuff for the new RS selection extensions am afraid; it just uses the usual matchesLabels stuff

**Comment by jimmidyson** [comment]
Don't be afraid! Was just mentioning it - sure it will be there soon enough :-b
