### ISSUE TITLE
ReplicaSets don't seem to appear when using OpenShift

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio-kubernetes#113]
I tried using this project which creates a ReplicaSet:
https://github.com/fabric8-quickstarts/funktion-java-example
via

```
mvn clean install fabric8:deploy
```

and I can see the ReplicaSet via the `oc get rs` command; but it doesn't appear in the Replicas tab in the console; I don't see it in the model either.

**Comment by gashcrumb** [comment]
Ah, didn't realize that was supported by openshift, requires removing this line of code:

https://github.com/hawtio/hawtio-kubernetes/blob/master/plugins/kubernetes/ts/watcher.ts#L275

**Comment by jstrachan** [comment]
DOH thanks!

**Comment by jstrachan** [comment]
just testing it here - will push a fix...
