### ISSUE TITLE
provide a 'configure' button on Deployments page

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio-kubernetes#127]
we now have lots of nice little UIs for editing the ConfigMap for an app. e.g. for a Deployment / DeploymentConfig "gogs", there's a nice UI for editing the ConfigMap for "gogs".

So it might be nice to have a configure button on Deployments when there's a ConfigMap of the same name; which would then link to the configmap edit page for that name

**Comment by gashcrumb** [comment]
On this page, right?  Maybe a button in the table when a configmap for that particular deployment is there?  Wonder, should we group 'scale' and this 'config' button into a single 'Actions' column?

![screenshot-localhost 9000 2016-09-08 13-45-16](https://cloud.githubusercontent.com/assets/351660/18360081/9c73b0a8-75ca-11e6-856a-1c714c624004.png)

**Comment by jstrachan** [comment]
Yeah, thats the page! 

I do kinda like the Pods + Scale being clear  (otherwise folks might wonder what the 2 numbers on a row was. I wonder if we right align the Configure button on the Name column? Or add the configure icon after the name?

**Comment by jstrachan** [comment]
Mind you I guess on the pods page we put all the 'Action' buttons for details / logs / console etc in a column called 'Status' :) So maybe a separate column is required for Actions?

**Comment by gashcrumb** [comment]
Yeah, `pods` already has a lot of columns, in my particular monitor layout I have to scroll sideways to see 'em all.  But there's already a `status` column at least for pods that we've currently used to sneak the terminal/log link.  Kinda thinking having a typical column `actions` might be the way to go to help all these views be consistent, can start with single links/icons and move to a menu if a view starts getting a lot of actions per row?

**Comment by jstrachan** [comment]
sounds good!

**Comment by gashcrumb** [comment]
Actually decided I didn't like how the button looked in the table there, so opted for your suggestion there, how's this:

![screenshot-localhost 9000 2016-09-08 16-30-31](https://cloud.githubusercontent.com/assets/351660/18365688/b2d41038-75e1-11e6-988d-f1f7a7b71910.png)

**Comment by jstrachan** [comment]
Lovely!!!
