### ISSUE TITLE
show nice icons for when a pod has started (but is not yet Ready - so its kinda running) and when its Terminating

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio-kubernetes#128]
we seem to only show icons for downloading and running mostly; we can probably show a few more nicer icons to give a better idea of the actual status

**Comment by astefanutti** [comment]
I've just pushed @d5e41e634c4cb245e00fee5f856f42c7253c87f4 that adds icons for the creation sequence (scheduled, pulled, created, started) as well as for the termination. Let me know your feedback on the code and the new icon set.

**Comment by astefanutti** [comment]
For the record, I gave a spin on trying to use a filter / directive for the status icon instead of embedding presentation information into the model with the `$statusCss` here astefanutti/hawtio-profiles@8b0d9eb05884b997b5efc32a30f55477cc3fbe8c. Let me know if that's something worth using as well.

**Comment by jimmidyson** [comment]
@astefanutti Do we use sass or less? Can we just create classes in generated CSS & use a class name derived from status rather than the big old switch stuff? More efficient client side & neater imo. Does that make sense?

**Comment by gashcrumb** [comment]
Yeah, we're using less in hawtio-kubernetes at least.  @astefanutti  That's still a nicer solution though with ng-switch.  Wonder if it'd be difficult to continue using the font awesome icons while also using just CSS classes for the states...

**Comment by astefanutti** [comment]
Oh sounds like a great idea. The filter would do the mapping and we could eventually get rid of the directive.

I propose that I merge @d5e41e6, if it's ok with you, so that we can get those nice status icons and I'll create a separate issue for the refactoring.

**Comment by gashcrumb** [comment]
@astefanutti sounds good to me!

**Comment by jstrachan** [comment]
@astefanutti awesome thanks!
