### ISSUE TITLE
Run... UI doesn't support PersistentVolumeClaim kinds

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio-kubernetes#130]
e.g. the gogs + nexus + jenkins apps now include those

**Comment by gashcrumb** [comment]
So it's the 404 you get when you try and run one of those then?

**Comment by jstrachan** [comment]
I managed to run the template OK, its just no PVC seemd to get created. I guess that code that applies the objects in a Template just doesn't use the right URI for the POST maybe.

Lemme attach some sample kubernetes + openshift catalog yaml to demonstrate...

**Comment by jstrachan** [comment]
Here's my local build of the app-catalog for kubernetes and openshift; which on kubernetes makes the configmaps (named catalog-foo) and on openshift it makes templates. 

https://gist.github.com/jstrachan/38e949c5277ea255f94629a0758d7835

To try install these on top of a regular install of fabric8 run one of these commands:

```
kubectl delete configmap -lkind=catalog
oc delete template --all
```

then one of these (depending on platform) 

```
kubectl apply -f https://gist.githubusercontent.com/jstrachan/38e949c5277ea255f94629a0758d7835/raw/fd04b01c913b50c1828d6c9b86bde5d67a4679c0/app-catalog-kubernetes.yml
oc apply -f https://gist.githubusercontent.com/jstrachan/38e949c5277ea255f94629a0758d7835/raw/fd04b01c913b50c1828d6c9b86bde5d67a4679c0/app-catalog-openshift.yml
```

**Comment by jstrachan** [comment]
BTW its gogs, nexus and jenkins which have PVCs inside them. You could test it out by deleting gogs D/DC and its PVC, then re-running the app from one of these templates from the console and seeing if the PVC get recreated

**Comment by gashcrumb** [comment]
Yeah, just gave it a go into a different namespace for just gogs, the POST for the PVC gets a 404, so just working on figuring out the right URL to use :-)

**Comment by jstrachan** [comment]
yeah :) Think its a regular kubernetes v1 entity btw - wonder if the code is assuming openshift?

**Comment by gashcrumb** [comment]
This should be all set once we get a new hawtio-kubernetes release out...

**Comment by jstrachan** [comment]
thanks!
