### ISSUE TITLE
the overview page should link to the Deployment / DeploymentConfig ideally rather than RC/RS

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio-kubernetes#132]
also would be nice to have a Configure button like the Deployment page maybe?

**Comment by gashcrumb** [comment]
Agreed!  I can take a look at this if you're not already on it...

**Comment by jstrachan** [comment]
@gashcrumb go for it! :)

**Comment by gashcrumb** [comment]
Wonder, should I assume the Deployment/Deployment config name is going to be the same as the app name?  Thinking I might try and get these associated with the app structure that we put together in KubernetesModel.

**Comment by jstrachan** [comment]
@gashcrumb yeah that sounds like a good default. as in if the names match, lets try associate them in the UI pages

**Comment by jstrachan** [comment]
I guess a Deployment / RC could refer to N different config maps in the env.valueFrom or volume metadata too really ;) - but assuming the names match sounds a nice simple default really - as a Deployment can use 0..N ConfigMaps really

**Comment by gashcrumb** [comment]
So what I was kinda thinking was to rework the current logic that creates the 'app' objects to just associated all the related objects via the Deployment/DeploymentConfig's selectors, would still though have to fall back onto using an RC's selector as well as for example fabric8-console doesn't use a Deployment looks like.  But then the 'app' object will have all the associated things uh...  associated :-)

Like this:
![capture](https://cloud.githubusercontent.com/assets/351660/18641887/87db9ee4-7e6c-11e6-8047-3f6635d0abec.PNG)

**Comment by jstrachan** [comment]
sounds good! For added complication the ConfigMaps are not associated using the selectors; they are in the `spec.container.env.valueFrom` object (for mapping configmap entries to env vars) or `spec.volume` for configmap volumes - so if you wanted to be totally accurate then we should use that metadata to do the association.

**Comment by gashcrumb** [comment]
Ah, I see, tricky!  I'll try and get that association made too, might as well make it accurate.

**Comment by jstrachan** [comment]
I guess lots of our apps have the same-name association (e.g. gogs, jenkins, nexus etc). For Volume association you could use this quickstart:
https://github.com/fabric8-quickstarts/spring-boot-webmvc/blob/master/src/main/fabric8/deployment.yml#L7

i.e. a volume of kind `configMap` then the name is inside that object. Don't have an env.valueFrom example to hand right now...

**Comment by gashcrumb** [comment]
Have the env.valueFrom part sorted, just have to handle volumes...

**Comment by jstrachan** [comment]
I guess if a D/Dc/app has > 1 config the config icon could generate a drop down to list them all by name?

**Comment by gashcrumb** [comment]
oh yeah, definitely that'd be ideal...
