### ISSUE TITLE
Utility menu shown in top right corner

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio-kubernetes#20]
Not sure what is the purpose or if it was some test code

![screen shot 2015-04-20 at 1 47 30 pm](https://cloud.githubusercontent.com/assets/477100/7229394/76ec7ef6-e763-11e4-9bae-38b98d448cac.png)

**Comment by gashcrumb** [comment]
Yeah, it's just a placeholder really, should probably come out of any actual console index.html file.

**Comment by davsclaus** [comment]
The User menu also has a link item. I guess we can disable them?

I assume the intention is that plugins can register menu items or something?
