### ISSUE TITLE
The connect dialog has little blue button

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio-kubernetes#21]
When trying to connect to a JVM container (eg jolokia)

![screen shot 2015-04-30 at 11 21 44 am](https://cloud.githubusercontent.com/assets/477100/7409926/b043e742-ef2a-11e4-8590-e0f6dab8474b.png)

Its the CSS style / html that is wrong. The red button is an input and the blue is a button, and then they get different shape and size.

```
<div class="modal-footer">
      <input class="btn btn-danger" ng-show="true" type="submit" value="Connect" ng-click="submit()">
      <button class="btn btn-primary ng-binding" ng-click="cancel()"></button>
    </div>
```

**Comment by jstrachan** [comment]
agreed. I suspect when on OpenShift we probably don't even need the user/pwd dialog too

**Comment by davsclaus** [comment]
The problem is the cancel button has no text, setting it to `Cancel` shows the button nicely.

**Comment by davsclaus** [comment]
Yeah not even sure if those values are in use. I just tried username = foo, and password = bar, on os1 and I connected to the library-app-jolokia pod
