### ISSUE TITLE
looks like switching between namespaces on the apps/services/controllers/pods pages are broken

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio-kubernetes#22]
just tried it and changing the selected namespace doesn't seem to have an effect

**Comment by jstrachan** [comment]
it works on the Diagram tab mind you!

**Comment by gashcrumb** [comment]
This works fine now with the new watcher service...  Except on the Diagram/overview tab!  :-)  Will open a separate issue for that...
