### ISSUE TITLE
Token is not used when connecting to pod

### ISSUE THREAD

**Issue by jimmidyson** [hawtio/hawtio-kubernetes#25]
This is fixed in openshift-jvm I think but not working in this kubernetes plugin? @gashcrumb Do you know how to fix this?

/cc @rhuss

**Comment by gashcrumb** [comment]
We just need to change how connecting is done from hawtio-kubernetes and
make sure the latest hawtio-jmx is being used.  Assign this issue to me,
I'll take care of it in a few...

**Comment by jimmidyson** [comment]
Thanks @gashcrumb!

**Comment by gashcrumb** [comment]
K, took some tweaks in a couple modules but this should be sorted:

1) https://github.com/hawtio/hawtio-kubernetes/commit/4133500ecf64e9609016e935ea0fb6c20b9ee3f6
2) https://github.com/hawtio/hawtio-jmx/commit/81ea7aa53fa2dea1a58e7d2ac84a62b65633632d

Updated fabric8-console as well and released a new tag -> https://github.com/fabric8io/fabric8-console/commit/ee7f7463cd4e3145f6ad16e64c9be726f36f06bb

One thing to watch out for, looks like for me locally the proxy is returning two values in the Access-Control-Allow-Origin header, so the browser rejects the invocation to jolokia, hopefully it's just a misconfiguration locally.

**Comment by rhuss** [comment]
thanks a lot, will try it.

**Comment by gashcrumb** [comment]
Is this all set?

**Comment by jimmidyson** [comment]
Working!
