### ISSUE TITLE
Overview page doesn't update when switching namespaces

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio-kubernetes#26]
You can switch 'em but the UI doesn't appear to update until you go elsewhere and come back to the page.

**Comment by davsclaus** [comment]
Is this still a problem today I wonder?

**Comment by gashcrumb** [comment]
Actually I think this should be all set, gave the overview a bit of love not too long ago, if you've got a chance to give it a quick test that'd be awesome, or I can check it later on today.

**Comment by gashcrumb** [comment]
Just took a second now, works fine for me.
