### ISSUE TITLE
Resize button on Apps page does not work

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio-kubernetes#27]
See the screenshot with details. When you click on that "hard to see button" then nothing happens. The tooltip says its for resizing the controller.

![reisize](https://cloud.githubusercontent.com/assets/477100/7931527/9f933140-0911-11e5-9917-b43a90eec295.png)

**Comment by gashcrumb** [comment]
Ah, didn't realize there's a resize button on the list view too, can't even see it!  In the normal view the pod count to the right also is a link to resize, maybe we should just have a similar column in this list view.

**Comment by gashcrumb** [comment]
Should probably come up with a consistent "resize" icon to use for this link on all 3 views.  Even in the normal app view you don't really know that there's a link there unless you hover the mouse over it.

**Comment by gashcrumb** [comment]
Actually opted to try and make the link more consistent across the 3 views, as I didn't wind up liking how the resize icon looked.  For the app list view I moved the replica count over to the right of the replication controller column so it's in a nice vertical line and more associated with the count of actual pods.

**Comment by gashcrumb** [comment]
Think this is all set
