### ISSUE TITLE
In the Apps page, the pods should be left aligned - today they are mid / right mixed

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio-kubernetes#30]
See screenshot.

I think the pods should be left aligned, then when you have 1, 2 or 3+ then its all showing nicely.

![apps](https://cloud.githubusercontent.com/assets/477100/8023460/974c4a12-0d0d-11e5-9503-26dd9e34ac3c.png)

**Comment by gashcrumb** [comment]
This used to be an issue but I thought it was fixed, have you cleared your cache recently?  Am not seeing it here...

**Comment by jstrachan** [comment]
I don't see it in hawtio-kubernetes; but do in fabric8-console. Wonder if its some CSS?

**Comment by jstrachan** [comment]
correctly - I get the same bug in Chrome on my mac with hawtio-kubernetes running locally too

**Comment by jstrachan** [comment]
correction - after flushing caches - I don't see this issue in either hawtio-kubernetes or fabric8-console locally - or in the docker container!

I did a `docker pull fabric8/fabric8-console` too and deleted the fabric8-console pod for good measure and its all working fine here

**Comment by davsclaus** [comment]
Yep just did the same as james, and there was a new version of the fabric8 console. And deleted all history on safari browser which I normally do not use. And now all of them is aligned nicely to the right.
