### ISSUE TITLE
Pod does not update status icon when pod is running

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio-kubernetes#39]
eg the status icon may show a download / pending state. And then a while later the image is downloaded and the pod is in running state.

The oc get pods shows the running state.

Leaving the web ui for about 1h or so (I was out) then came back and the UI still have the status icon as downloading. The pods has been running for 1h

![screen shot 2015-06-23 at 11 30 16 am](https://cloud.githubusercontent.com/assets/477100/8304211/65d05ec6-19a4-11e5-8110-ca0af98150f5.png)

**Comment by jstrachan** [comment]
tried to fix this one - polished the code so am sure we definitely update the $statusCss property on a pod - but for some reason dynamically changing the css style inside:

```
    <i class="fa {{entity.$statusCss}}"></i>
```

does not actually refresh the icon. I suspect its a bootstrap issue? We may need a directive to deal with dynamic icons maybe...

**Comment by gashcrumb** [comment]
Most likely it's because 'entity' is different when an update occurs and what's displayed has a handle on the old instance instead.

**Comment by gashcrumb** [comment]
This should be alright now if you don't mind checking after a `bower update`

**Comment by jstrachan** [comment]
awesome - its working great now!!!
