### ISSUE TITLE
updates to the Pod page turn off sorting of the table

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio-kubernetes#43]

**Comment by gashcrumb** [comment]
I'm not sure if hawtio-simple-table even supports sorting really, ideally it should be possible to sort by any column just by clicking on it.  Will investigate anyways...

**Comment by jstrachan** [comment]
it does seem to startup sorting things - and showing a sortable highlight on the column - then if the table updates later or you click the headings it disappears ;)

**Comment by gashcrumb** [comment]
Seems to still be an issue with the table when clicking on other headers, but it's a little better.  The above commit did seem to address #39 though at least :-)

**Comment by jstrachan** [comment]
aha - its working fine now thanks!!! Yay! And sorting by clicking a column header is back again!
