### ISSUE TITLE
The app page shows too long description

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio-kubernetes#44]
I installed the camel-servlet quickstart from SNAPSHOT with

davsclaus:~/workspace/quickstarts/quickstarts/war (541)/$ mvn clean install docker:build fabric8:apply

And then the apps page shows it as an app and notice the very long description

![screen shot 2015-06-24 at 11 47 57 am](https://cloud.githubusercontent.com/assets/477100/8327109/30a69f7c-1a66-11e5-86ca-e9af3c7bca7f.png)

**Comment by gashcrumb** [comment]
Yeah, should define a max-height for the div holding the text _or_ truncate and provide a 'more...' link that maybe opens up a dialog with the full text so the user can read it.
