### ISSUE TITLE
the default selected namespace seems a little random - I wonder if we can default to `default` or store the last namespace in localhost?

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio-kubernetes#49]

**Comment by gashcrumb** [comment]
Hmm, I thought I had that storing in local storage, but maybe not.  We do fetch the namespaces up front before bootstrap, think maybe I'll just go through and ensure the various spots where we get the namespace is consistent, and also store the last selected namespace in local storage if it isn't.
