### ISSUE TITLE
add the service app links (the icon view from the Services tab) to the perspective stuff...

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio-kubernetes#51]
... so there's a top level quick way to switch between all the apps available inside kubernetes - with the icons.

FWIW `model.serviceApps` is an array of all the apps that have a $serviceUrl to click; then $iconUrl is the icon name

**Comment by gashcrumb** [comment]
BTW, wasn't sure of the best name for the nav entry, feel free to change it as necessary, it's in [this file](https://github.com/hawtio/hawtio-kubernetes/blob/master/plugins/kubernetes/html/serviceApps.html#L3)
