### ISSUE TITLE
JVM connect button - Please open in new tab

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio-kubernetes#57]
This is the most annoying that it opens in same window. You want to use the current window as the fabric8 web console, and then you may want to JVM connect to 1 or more pods, but in separate tabs. For example to see a AMQ broker, and another pod with a Camel route that routes to/from the broker.

Also all the other buttons for logs / metrics etc should open in separate tab, so users can keep the current window as the main fabric8 web console.

**Comment by davsclaus** [comment]
Those other buttons is a mix of behavior today so you are a bit confused, and "scared" what happens.

**Comment by davsclaus** [comment]
Its a new browser tab I refer to, like when you do ctrl + t.

**Comment by gashcrumb** [comment]
Yeah definitely should do this, especially given that most of these links aren't standard anchor tags, so you can't right-click and hit "Open in new tab"

**Comment by gashcrumb** [comment]
Got all the spots I know about, if there's other ones feel free to open new issues to point 'em out :-)
