### ISSUE TITLE
need a LogOut button

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio-kubernetes#61]
which on OpenShift / Google OAuth will zap the localStorage and force a relogin

**Comment by gashcrumb** [comment]
Really needs this -> https://github.com/hawtio/hawtio-oauth/issues/8

**Comment by gashcrumb** [comment]
Fixed in hawtio-oauth 2.0.29

**Comment by davsclaus** [comment]
Ah yeah are we all set for a logout button?

**Comment by gashcrumb** [comment]
Hm, just checking the console now and it's not showing up, will need to look into it.
