### ISSUE TITLE
the Open > link on the console uses the Route host name and the service port. We should not use the service port for route URLs

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio-kubernetes#65]
e.g. this link:

 http://quickstart-camelservlet.vagrant.f8:9101/ 

should not include the service port 9101

**Comment by davsclaus** [comment]
Here is a screenshot with example

![screen shot 2015-07-15 at 10 40 58 am](https://cloud.githubusercontent.com/assets/477100/8694148/16d74d8a-2add-11e5-822e-fc3b02d43892.png)

**Comment by davsclaus** [comment]
@gashcrumb you have any tips where this code is that shows this menu and populate it?

**Comment by davsclaus** [comment]
Ah found it here
https://github.com/hawtio/hawtio-kubernetes/blob/master/plugins/kubernetes/ts/kubernetesPlugin.ts#L162-162

**Comment by jstrachan** [comment]
here's the rendering code
https://github.com/hawtio/hawtio-kubernetes/blob/master/plugins/kubernetes/html/serviceApps.html#L8-8

the link is created here
https://github.com/hawtio/hawtio-kubernetes/blob/master/plugins/kubernetes/ts/kubernetesModel.ts#L271-271

looks like its a bug in this function
https://github.com/hawtio/hawtio-kubernetes/blob/master/plugins/kubernetes/ts/kubernetesHelpers.ts#L413-413

which should ignore the port if its a route host (rather than a portal IP)

**Comment by davsclaus** [comment]
Yeah I am using the same link as on the services page

**Comment by jstrachan** [comment]
yay!
