### ISSUE TITLE
Connect to JVM in pod do not work

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio-kubernetes#81]
Installed the Camel quickstart such as servlet/camel-war

The pod is installed and camel and tomcat runs fine. But the JVM connect in hawtio do not work.

![screen shot 2015-09-28 at 2 52 43 pm](https://cloud.githubusercontent.com/assets/477100/10135728/a394d4ec-65f0-11e5-9a60-9af2d606f944.png)

**Comment by davsclaus** [comment]
This is version 2.2.35 running in my local vagrant

**Comment by davsclaus** [comment]
Yeah its a missing header in the allowed CORS

![screen shot 2015-09-28 at 2 57 44 pm](https://cloud.githubusercontent.com/assets/477100/10135820/2a8420ac-65f1-11e5-8af2-e011b9a6078c.png)

**Comment by davsclaus** [comment]
OS issue logged 
https://github.com/openshift/origin/issues/4497

**Comment by gashcrumb** [comment]
We're also tracking this in hawtio-jmx here -> https://github.com/hawtio/hawtio-jmx/issues/10

**Comment by davsclaus** [comment]
We got a bunch of other tickets about this. @rhuss is working on updating and cleaning up the base image and setup jolokia correctly there
