### ISSUE TITLE
Remove select box in the select workspace page

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio-kubernetes#83]
When you open the web console then it shows the namespaces (workspace)

The selectbox [x] do not make any sence as there is no function for it, also its cleared when the ui updates itself.

![screen shot 2015-10-01 at 2 34 58 pm](https://cloud.githubusercontent.com/assets/477100/10220671/7e7877d0-6849-11e5-9dce-b55245cdbd70.png)

**Comment by jstrachan** [comment]
we need to be able to delete workspaces though; maybe thats best on this page?

**Comment by gashcrumb** [comment]
We've a delete button now so that selection box is applicable
