### ISSUE TITLE
Camel plugin - The sub tabs are now gone

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio-kubernetes#87]
eg where you can select "route diagram" "source" and so on.

![screen shot 2015-10-05 at 4 09 48 pm](https://cloud.githubusercontent.com/assets/477100/10282466/681700d0-6b7b-11e5-8c9b-bd3fabeaf7b4.png)

**Comment by davsclaus** [comment]
I guess some nav bar is gone, where you had "Camel", "JMX" etc.

**Comment by gashcrumb** [comment]
@jstrachan Wonder, maybe it's worth using a separate page for Java stuff so we can maintain the old nav bar for those views for now...

**Comment by gashcrumb** [comment]
Java console is now a completely separate page from the fabric8 console, think this should be all set.

**Comment by davsclaus** [comment]
assume this works now
