### ISSUE TITLE
The scale button to scale up/down pods is broken again

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio-kubernetes#90]
Version: 1.0.72

When clicking the replicas button to scale up you see a black screen

![screen shot 2015-10-26 at 2 15 49 pm](https://cloud.githubusercontent.com/assets/477100/10729736/aac8cae6-7beb-11e5-8cd0-aafc4b6b92a7.png)

**Comment by davsclaus** [comment]
@gashcrumb we had this bug before, wasn't it fixed in the past?

**Comment by gashcrumb** [comment]
Think James fixed it late friday, might just need a new release...

**Comment by jimmidyson** [comment]
Any chance of some UI tests to check stuff like this doesn't regress? No that's not me volunteering ;)

**Comment by jstrachan** [comment]
seems 2.2.60 has a bad build of the console - the latest image is working fine. So we just need a release

**Comment by jstrachan** [comment]
@jimmidyson it'd be hard to catch this bug TBH; as the UI works - its just modal dialogs are not visible to the user (but are in the DOM)

**Comment by jimmidyson** [comment]
Wouldn't using something like phantomjs & tests show that though?

**Comment by davsclaus** [comment]
I have not seen this problem anymore for a while
