### ISSUE TITLE
When you exit the angry pods then FPS counter is still visible

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio-kubernetes#91]
See screesnhot in the lower left corner. Maybe that FPS counter should be in the preference so you can turn it on|off, and leave it off by default?

![screen shot 2015-10-26 at 2 26 33 pm](https://cloud.githubusercontent.com/assets/477100/10729951/382dd8c6-7bed-11e5-87de-326fc1f4778b.png)

**Comment by davsclaus** [comment]
@gashcrumb I noticed this still is the case.

**Comment by gashcrumb** [comment]
@davsclaus because I haven't fixed it yet :-)

**Comment by gashcrumb** [comment]
yay, tracked down how to turn it off, don't think we really need a preference item for it :-)
